/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import javax.swing.JOptionPane;

/**
 *
 * @author YUMI
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_Contrasena = new javax.swing.JPasswordField();
        btn_Aceptar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        cbo_tipo = new javax.swing.JComboBox<String>();
        txt_Usuario = new javax.swing.JTextField();
        btn_NuevoUsuario = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/list_add_user.png"))); // NOI18N
        jLabel1.setText("Usuario:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 120, -1));

        jLabel2.setFont(new java.awt.Font("Bradley Hand ITC", 1, 18)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/document_encrypt.png"))); // NOI18N
        jLabel2.setText("Contraseña:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        txt_Contrasena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ContrasenaActionPerformed(evt);
            }
        });
        getContentPane().add(txt_Contrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 167, -1));

        btn_Aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/ok.png"))); // NOI18N
        btn_Aceptar.setText("Aceptar");
        btn_Aceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Aceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        btn_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/edit_delete_mail.png"))); // NOI18N
        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, -1, -1));

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/stop.png"))); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, 90, -1));

        cbo_tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Encargado Mesa Partes", "Modelador", "Gerente" }));
        cbo_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbo_tipoActionPerformed(evt);
            }
        });
        getContentPane().add(cbo_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 170, -1));
        getContentPane().add(txt_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 60, 167, -1));

        btn_NuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/news_subscribe.png"))); // NOI18N
        btn_NuevoUsuario.setText("Nuevo");
        btn_NuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_NuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 90, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ContrasenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ContrasenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ContrasenaActionPerformed

    private void btn_AceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AceptarActionPerformed
                
      pkgModelo.clsDAOLogin obj = new pkgModelo.clsDAOLogin();
      obj.setUsuario(cbo_tipo.getSelectedItem().toString().trim());
      //obj.setUsuario(txt_Usuario.getText().trim());
      obj.setContrasena(txt_Contrasena.getText().trim());
      String password = new String(txt_Contrasena.getPassword());
      
      if (cbo_tipo.getSelectedItem().toString().equals("Encargado Mesa Partes")&& password.equals("admin")) {
            FrmNuevoDocumento NuevoDocumento=new FrmNuevoDocumento();
            NuevoDocumento.setVisible(true);
            //this.setVisible(true);
            FrmLogin.this.dispose();
            //oo9988  this.setBounds(50, 50, 450, 240);
        } if (cbo_tipo.getSelectedItem().toString().equals("Modelador")&& password.equals("admin")){
            FrmCrearProcesos CrearProcesos=new FrmCrearProcesos();
            CrearProcesos.setVisible(true);
           // FrmLogin.this.dispose();
            
        } if (cbo_tipo.getSelectedItem().toString().equals("Gerente")&& password.equals("admin")){
            FrmEjecucionProceso EjecucionProceso=new FrmEjecucionProceso();
            EjecucionProceso.setVisible(true);
            //FrmLogin.this.dispose();
        }
      
//      if (obj.valide()== false) {
//          JOptionPane.showMessageDialog(rootPane, "Datos incorrectos");
//          
//      }
//      else{
//          java.awt.EventQueue.invokeLater(new Runnable(){
//              public void run(){
//              //new FrmCrearProcesos().setVisible(true);
//                  //cbo_tipoActionPerformed(java.awt.event.ActionEvent evt);
//          }
//          });
//          this.dispose();
//      }
    }//GEN-LAST:event_btn_AceptarActionPerformed

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        txt_Contrasena.setText(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void btn_NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoUsuarioActionPerformed
        // TODO add your handling code here:
        FrmUsuario Principal=new FrmUsuario();
        Principal.setVisible(true);
        FrmLogin.this.dispose();
    }//GEN-LAST:event_btn_NuevoUsuarioActionPerformed

    private void cbo_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbo_tipoActionPerformed
        // TODO add your handling code here:
//        if (cbo_tipo.getSelectedItem().equals("Encargado Mesa Partes")) {
//            FrmNuevoDocumento NuevoDocumento=new FrmNuevoDocumento();
//            NuevoDocumento.setVisible(true);
//            //FrmLogin.this.dispose();
//            //oo9988  this.setBounds(50, 50, 450, 240);
//        } else if (cbo_tipo.getSelectedItem().equals("Modelador")) {
//            FrmCrearProcesos CrearProcesos=new FrmCrearProcesos();
//            CrearProcesos.setVisible(true);
//           // FrmLogin.this.dispose();
//            
//        } else if (cbo_tipo.getSelectedItem().equals("Gerente")) {
//            FrmEjecucionProceso EjecucionProceso=new FrmEjecucionProceso();
//            EjecucionProceso.setVisible(true);
//            //FrmLogin.this.dispose();
//        }
    }//GEN-LAST:event_cbo_tipoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Aceptar;
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_NuevoUsuario;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JComboBox<String> cbo_tipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txt_Contrasena;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
