/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgVista;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import pkgControlador.clsConecta;

/**
 *
 * @author YUMI
 */
public class FrmUsuario extends javax.swing.JFrame {
DefaultTableModel model;
Connection Conn;
Statement sent;

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
        Llenar();
        Deshabilitar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Usuario = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbo_Cargo = new javax.swing.JComboBox();
        txt_Contraseña = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_NombApellidos = new javax.swing.JTextField();
        btn_NuevoUsuario = new javax.swing.JButton();
        btn_GuardarUsuario = new javax.swing.JButton();
        btn_ModificarUsuario = new javax.swing.JButton();
        btn_EliminarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_Usuario = new javax.swing.JTable();
        btn_Salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cargo");

        txt_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_UsuarioActionPerformed(evt);
            }
        });

        jLabel2.setText("Usuario");

        jLabel3.setText("Contraseña");

        cbo_Cargo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Encargado Mesa Partes", "Modelador", "Gerente" }));

        jLabel4.setText("Nombre y Apellidos");

        btn_NuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/news_subscribe.png"))); // NOI18N
        btn_NuevoUsuario.setText("Nuevo");
        btn_NuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NuevoUsuarioActionPerformed(evt);
            }
        });

        btn_GuardarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/save_all.png"))); // NOI18N
        btn_GuardarUsuario.setText("Grabar");
        btn_GuardarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarUsuarioActionPerformed(evt);
            }
        });

        btn_ModificarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/edit.png"))); // NOI18N
        btn_ModificarUsuario.setText("Modificar");
        btn_ModificarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ModificarUsuarioActionPerformed(evt);
            }
        });

        btn_EliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/edit_delete_shred.png"))); // NOI18N
        btn_EliminarUsuario.setText("Eliminar");
        btn_EliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EliminarUsuarioActionPerformed(evt);
            }
        });

        tabla_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla_Usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_UsuarioMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_Usuario);

        btn_Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgIconos/stop.png"))); // NOI18N
        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbo_Cargo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txt_NombApellidos)
                                            .addComponent(txt_Contraseña)))))
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_Salir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_NuevoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_GuardarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_ModificarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_EliminarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(cbo_Cargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txt_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txt_Contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_NombApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btn_NuevoUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_GuardarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_ModificarUsuario)
                        .addGap(7, 7, 7)
                        .addComponent(btn_EliminarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Salir)))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    void Deshabilitar(){
        txt_Usuario.setEditable(false);
        txt_Contraseña.setEditable(false);
        txt_NombApellidos.setEditable(false);
    }
    void Limpiar(){
        txt_Usuario.setText("");
        txt_Contraseña.setText("");
        txt_NombApellidos.setText("");
    }
    void Habilitar(){
        txt_Usuario.setEditable(true);
        txt_Contraseña.setEditable(true);
        txt_NombApellidos.setEditable(true);
    }
    void Llenar(){
    try{
        Conn=clsConecta.getConnection();
        String [] titulos ={"Usuario","Contraseña", "NombreyApellidos","Cargo"};
        String sql="select nombre_usuario,clave_usuario,nombre_completo, cargo from usuario";
        model=new DefaultTableModel(null, titulos);
        sent=Conn.createStatement();
        ResultSet rs=sent.executeQuery(sql);

        String fila []= new String [5];

        while(rs.next()){
            fila [0]=rs.getString("nombre_usuario");
            fila [1]=rs.getString("clave_usuario");
            fila [2]=rs.getString("nombre_completo");
            fila [3]=rs.getString("cargo");

            model.addRow(fila);

        }
        tabla_Usuario.setModel(model);

            }catch(Exception e){
        e.printStackTrace();
            }
}
    private void btn_NuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NuevoUsuarioActionPerformed
        // TODO add your handling code here:
        Limpiar();
        Habilitar();
    }//GEN-LAST:event_btn_NuevoUsuarioActionPerformed

    private void btn_EliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EliminarUsuarioActionPerformed
        // TODO add your handling code here:
        try{
            int fila=tabla_Usuario.getSelectedRow();
            String sql="delete from usuario where nombre_usuario="+tabla_Usuario.getValueAt(fila,0);
            sent=Conn.createStatement();
            int n=sent.executeUpdate(sql);
            if(n>0){
                Llenar();
                JOptionPane.showMessageDialog(null, "datos eliminados");
                Limpiar();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "error"+e.getMessage());
        }
    }//GEN-LAST:event_btn_EliminarUsuarioActionPerformed

    private void btn_GuardarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarUsuarioActionPerformed
        // TODO add your handling code here:
        try{
            String sql="insert into usuario (nombre_usuario, clave_usuario, nombre_completo, cargo)" +
                   "Values (?,?,?,?) ";
            PreparedStatement ps=Conn.prepareCall(sql);
            ps.setString(1, txt_Usuario.getText());
            ps.setString(2, txt_Contraseña.getText());
            ps.setString(3, txt_NombApellidos.getText());
            ps.setString(4, cbo_Cargo.getSelectedItem().toString());
            
            int n=ps.executeUpdate();
            if(n>0)
            JOptionPane.showMessageDialog(null, "datos guardados");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "error"+ e.getMessage());
        }
        Llenar();
        Limpiar();
    }//GEN-LAST:event_btn_GuardarUsuarioActionPerformed

    private void tabla_UsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_UsuarioMouseClicked
        // TODO add your handling code here:
        int i = tabla_Usuario.getSelectedRow();
        Habilitar();
        TableModel model = tabla_Usuario.getModel();
         cbo_Cargo.getSelectedItem().toString();
         txt_Usuario.setText(model.getValueAt(i,0).toString());
         txt_Contraseña.setText(model.getValueAt(i,1).toString());
         txt_NombApellidos.setText(model.getValueAt(i,2).toString());
//        if(evt.getButton()==1){
//            int fila=tabla_Usuario.getSelectedRow();
//            try{
//                Habilitar();
//                 
//                 String sql="select * from usuario where id_usuario="+tabla_Usuario.getValueAt(fila,0);
//                 sent=Conn.createStatement();
//                 ResultSet rs=sent.executeQuery(sql);
//                 rs.next();
//                 cbo_Cargo.getSelectedItem().toString();
//                 txt_Usuario.setText(rs.getString("nombre_usuario"));
//                 txt_Contraseña.setText(rs.getString("clave_usuario"));
//                 txt_NombApellidos.setText(rs.getString("nombre_completo"));
//                 
//
//            }catch(Exception e){
//                e.printStackTrace();
//            }
//        }
    }//GEN-LAST:event_tabla_UsuarioMouseClicked

    private void btn_ModificarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ModificarUsuarioActionPerformed
        // TODO add your handling code here:
        try{
            String sql="Update usuario set nombre_usuario=?, clave_usuario=?, nombre_completo=?, cargo=?"+
                    "where id_usuario=?";
            int fila=tabla_Usuario.getSelectedRow();
            String dao=(String)tabla_Usuario.getValueAt(fila,0);
            PreparedStatement ps=Conn.prepareCall(sql);
            ps.setString(1, txt_Usuario.getText());
            ps.setString(2, txt_Contraseña.getText());
            ps.setString(3, txt_NombApellidos.getText());
            ps.setString(4, cbo_Cargo.getSelectedItem().toString());

           ps.setString(5,dao);
            int n=ps.executeUpdate();
            if(n>0){
                Limpiar();
                Llenar();
                JOptionPane.showMessageDialog(null, "datos modificados");

            }
        }catch (Exception e){
            JOptionPane.showMessageDialog(null, "error"+ e.getMessage());
        }
    }//GEN-LAST:event_btn_ModificarUsuarioActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void txt_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_UsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_EliminarUsuario;
    private javax.swing.JButton btn_GuardarUsuario;
    private javax.swing.JButton btn_ModificarUsuario;
    private javax.swing.JButton btn_NuevoUsuario;
    private javax.swing.JButton btn_Salir;
    private javax.swing.JComboBox cbo_Cargo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_Usuario;
    private javax.swing.JTextField txt_Contraseña;
    private javax.swing.JTextField txt_NombApellidos;
    private javax.swing.JTextField txt_Usuario;
    // End of variables declaration//GEN-END:variables
}
